theme: jekyll-theme-minimal
plugins:
 - jekyll-theme-minimal

# Site info
title: The Monkey Scripts
description: My UserScripts collection for FireMonkey (the other monkeys will probably work too)
show_downloads: false
